FROM @@IMAGE@@

RUN apt-get -y update && \
    apt-get -y install curl git zsh vim tmux
RUN locale -a

#RUN test -e /etc/locale.conf && cat /etc/locale.conf || true
#RUN test -e /etc/locale.conf || sudo localectl set-locale LANG=en_US.UTF-8

ADD .github/docker/entrypoint* /
RUN chmod +x /entrypoint*